User.create(name: '斉藤', age: 35, sex: 1)
User.create(name: '田中', age: 21, sex: 2)
User.create(name: '佐藤', age: 32, sex: 1)
User.create(name: '山岸', age: 33, sex: 1)
User.create(name: '平', age: 26, sex: 2)
User.create(name: '加藤', age: 25, sex: 2)